### ISSUE TITLE
megamdocker postremove needs to remove pipeworks and log files

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/gitpackager#209]

**Comment by indykish** [comment]
@thomasalrin  fixed  ?

**Comment by thomasalrin** [comment]
@indykish it is not fixed yet. We shall do it, when we install megamdocker.

**Comment by indykish** [comment]
ok.

**Comment by indykish** [comment]
@ranjithamca  Please make sure the package is clean, i find things that shouldn't be there. 

@vijaykanthm28  @rajesh-rajagopal  fyi.

**Comment by ranjithamca** [comment]
fixed #209
