### ISSUE TITLE
nsqd persists files as .dat files under $HOME, shall be under /var/lib/megam/vertice/nsqd

### ISSUE THREAD

**Issue by indykish** [megamsys/gitpackager#221]
@vijaykanthm28  When you start nsqd there is a parameter to set it up.

**Comment by indykish** [comment]
ExecStart=/usr/share/megam/nsqd/bin/nsqd --lookupd-tcp-address=127.0.0.1:4160 -data-path=/var/lib/megam/vertice/nsqd

**Comment by indykish** [comment]
@vijaykanthm28  Is this done ?

**Comment by ranjithamca** [comment]
closed #221
