### ISSUE TITLE
vertice nilavu cannot install dependency ruby2.3 ruby2.3-dev

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gitpackager#244]
we used to install 
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.3 ruby2.3-dev 

we have to add to preinstall

**Comment by indykish** [comment]
There is no 2.3 package in trusty. You will have to point to 2.2.x in trusty.
http://packages.ubuntu.com/search?keywords=ruby2.3

**Comment by ranjithamca** [comment]
close #244
