### ISSUE TITLE
vertice can't restart automatically

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/gitpackager#246]
Sep 12 11:11:40 megamswasa vertice[5100]:      '--'
Sep 12 11:11:40 megamswasa vertice[5100]: [151B blob data]
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=warning msg="skip metricsd service."
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="writing CPU profile to: cpuprof"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="writing mem profile to: memprof"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mone "
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=debug msg="\x1b[1;34;10m  > one initialized\x1b[0m"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="\x1b[1;37;10m  > one \x1b[0m\t\x1b[0;36;10mready\x1b
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="starting httpd service"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mdocker "
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=debug msg="\x1b[1;34;10m  > docker initialized\x1b[0m"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="\x1b[1;37;10m  > docker \x1b[0m\t\x1b[0;36;10mready\
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=debug msg="\x1b[1;32;10mō͡≡o˞̶  engine up\x1b[0m"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="  > httpd http://192.168.0.118:7777"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="starting deployd service"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="starting eventsd service"
Sep 12 11:11:40 megamswasa vertice[5100]: time="2016-09-12T11:11:40+05:30" level=info msg="starting dockerd service"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP6026737942425412819"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP7209508850882454485"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP7731095047421208979"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP7437008564853327461"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP5594552607199783850"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="list requests RIP4721058774494023676"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=info msg="WRIT user onboard"
Sep 12 11:11:41 megamswasa vertice[5100]: 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial tcp 192.168.0.116:904
Sep 12 11:11:41 megamswasa vertice[5100]: -- ks <nil>&carton.Requests{Id:"", Name:"", CatId:"", Action:"", Category:"", CreatedAt:""}time="2016
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table requests\x1b[0m"
Sep 12 11:11:41 megamswasa vertice[5100]: 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial tcp 192.168.0.116:904
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] Connection close\x1b[0m"
Sep 12 11:11:41 megamswasa vertice[5100]: 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial tcp 192.168.0.116:904
Sep 12 11:11:41 megamswasa vertice[5100]: -- ks <nil>-- ks <nil>2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial
Sep 12 11:11:41 megamswasa vertice[5100]: -- ks <nil>panic: runtime error: invalid memory address or nil pointer dereference
Sep 12 11:11:41 megamswasa vertice[5100]:         panic: runtime error: invalid memory address or nil pointer dereference
Sep 12 11:11:41 megamswasa vertice[5100]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x69c1ee]
Sep 12 11:11:41 megamswasa vertice[5100]: goroutine 25 [running]:
Sep 12 11:11:41 megamswasa vertice[5100]: panic(0xaa6a40, 0xc42000e050)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/software/go/src/runtime/panic.go:500 +0x1a1
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/libgo/db.(*ScyllaDB).Close(0x0)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/db/scylladb.go:65 +0xae
Sep 12 11:11:41 megamswasa vertice[5100]: panic(0xaa6a40, 0xc42000e050)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/software/go/src/runtime/panic.go:458 +0x243
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/libgo/db.(*ScyllaDB).table(0x0, 0xb7a2eb, 0x8, 0xc4202ba0d0, 0x1, 0x1, 0x10c2ec0,
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/db/scylladb.go:60 +0xfa
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/libgo/db.(*ScyllaDB).newScyllaTable(0x0, 0xb7a2eb, 0x8, 0xc4202ba0d0, 0x1, 0x1, 0
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/db/scylla.go:39 +0x271
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/libgo/db.Fetchdb(0xb7a2eb, 0x8, 0xc4202ba0d0, 0x1, 0x1, 0x10c2ec0, 0x0, 0x0, 0x0,
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/db/scylla.go:46 +0x10b
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/vertice/carton.listReqsById(0xc420432080, 0x16, 0xc420432080, 0x16, 0xc42040c000)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/payload.go:81 +0x3
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/vertice/carton.(*Payload).Convert(0xc42040c000, 0x84, 0x84, 0xc42040c000)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/payload.go:53 +0x6
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ(0xc4201e1740, 0xc42040a000)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/service.go:7
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/vertice/subd/deployd.(*Service).(github.com/megamsys/vertice/subd/deployd.process
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/service.go:4
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/crackcomm/nsqueue/consumer.(*queue).HandleMessage(0xc420267e80, 0xc42028ca80, 0xb68f00, 0x
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/.go/src/github.com/crackcomm/nsqueue/consumer/queue.go:13 +0x60
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/nsqio/go-nsq.(*Consumer).handlerLoop(0xc4201d8300, 0x10851c0, 0xc420267e80)
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/.go/src/github.com/nsqio/go-nsq/consumer.go:1105 +0x14a
Sep 12 11:11:41 megamswasa vertice[5100]: created by github.com/nsqio/go-nsq.(*Consumer).AddConcurrentHandlers
Sep 12 11:11:41 megamswasa vertice[5100]:         /home/alrin/.go/src/github.com/nsqio/go-nsq/consumer.go:1087 +0xaa
Sep 12 11:11:41 megamswasa systemd[1]: vertice.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 12 11:11:41 megamswasa systemd[1]: vertice.service: Unit entered failed state.
Sep 12 11:11:41 megamswasa systemd[1]: vertice.service: Failed with result 'exit-code'.

**Comment by indykish** [comment]
@vijaykanthm28  Did you look at the panic ? 

It seems when  `cassandra` is not up, and vertice is started we crash. 

Can you fix it up by providing a message saying `can't start as ,  cassandra is down. `

```
Sep 12 11:11:41 megamswasa vertice[5100]: 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial tcp 192.168.0.116:904
Sep 12 11:11:41 megamswasa vertice[5100]: time="2016-09-12T11:11:41+05:30" level=debug msg="\x1b[1;34;10m > [scylla] Connection close\x1b[0m"
Sep 12 11:11:41 megamswasa vertice[5100]: 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial tcp 192.168.0.116:904
Sep 12 11:11:41 megamswasa vertice[5100]: -- ks -- ks 2016/09/12 11:11:41 gocql: unable to dial control conn 192.168.0.116:9042: dial
Sep 12 11:11:41 megamswasa vertice[5100]: -- ks panic: runtime error: invalid memory address or nil pointer dereference
Sep 12 11:11:41 megamswasa vertice[5100]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 12 11:11:41 megamswasa vertice[5100]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x69c1ee]
Sep 12 11:11:41 megamswasa vertice[5100]: goroutine 25 [running]:
Sep 12 11:11:41 megamswasa vertice[5100]: panic(0xaa6a40, 0xc42000e050)
Sep 12 11:11:41 megamswasa vertice[5100]: /home/alrin/software/go/src/runtime/panic.go:500 +0x1a1
Sep 12 11:11:41 megamswasa vertice[5100]: github.com/megamsys/libgo/db.(ScyllaDB).Close(0x0)
```

**Comment by vijaykanthm28** [comment]
@indykish 
No ( we have disabled the health check for database and queue ), it will crash any request start process when cassandra is down 
we may health check to fix it

**Comment by indykish** [comment]
@vijaykanthm28  Why can't we gracefully quit saying  ? Refer my original msg.

Can you fix it up by providing a message saying can't start as , cassandra is down.

**Comment by indykish** [comment]
@vijaykanthm28  Fixed  ? I think so.

**Comment by vijaykanthm28** [comment]
@indykish  its still issue because in trusty package upstart automatically restarts the vertice while it gets stop (panic). In service script it doesn't restart vertice

**Comment by indykish** [comment]
@vinomca-megam   Probably when you open an issue, please elaborate the problem.

@vijaykanthm28  I don't understand the problem we are trying to fix here. 

Can you elaborate the problem so we can find a soln ?

**Comment by vijaykanthm28** [comment]
when cassandra is down it will not panic its fixed so close the issue @vinomca-megam
