### ISSUE TITLE
verticegulp systemd needs a change in the permission bits.

### ISSUE THREAD

**Issue by indykish** [megamsys/gitpackager#262]
Here is the message i see in `vnc viewer`.

![screenshot from 2016-10-13 22-13-10](https://cloud.githubusercontent.com/assets/1402479/19358117/45c92434-9192-11e6-9baf-0c704d852973.png)

FIX:   `chmod <figure out the bit>> /etc/systemd/verticegulp..sevice`

**Comment by indykish** [comment]
@rajesh-rajagopal  Is this done ?

**Comment by rajesh-rajagopal** [comment]
Removed executable permission in debian image. kindly close this issue
