### ISSUE TITLE
/usr/share/megam/verticenilavu is now /var/lib/www/

### ISSUE THREAD

**Issue by indykish** [megamsys/gitpackager#265]
### We don't need /usr/share/megam/verticenilavu ?

Why are we still having that ? 

### We show a null $Rails.root in the /var/lib/www directory ? 

![screenshot from 2016-10-15 20-13-29](https://cloud.githubusercontent.com/assets/1402479/19410912/b025beea-9314-11e6-88a7-e88353057965.png)

Guys @ranjithamca @rajesh-rajagopal  please pay attention to details.

**Comment by rajesh-rajagopal** [comment]
right now we are not create the /usr/share/megam/verticenilavu directory
