### ISSUE TITLE
"service verticenilavu start" starts verticenilavu in foreground

### ISSUE THREAD

**Issue by indykish** [megamsys/gitpackager#266]
I had to do 

```
service verticenilavu start &` 
```

in cloud.det.io

@rajesh-rajagopal   Is this the way you guys start in our staging ?

**Comment by rajesh-rajagopal** [comment]
service verticenilavu start is not working.
use **sv start unicorn** for starting nilavu & **sv stop unicorn** for stop nilavu.

**Comment by indykish** [comment]
Ok. thanks. closing this issue.
