### ISSUE TITLE
remove verticevnc post install error

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gitpackager#316]
megam@cloud-det-io:/var/lib/backup$ sudo apt-get purge virtenginevnc 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  virtenginevnc*
0 upgraded, 0 newly installed, 1 to remove and 88 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 47848 files and directories currently installed.)
Removing virtenginevnc (1.5-4) ...
Purging configuration files for virtenginevnc (1.5-4) ...
dpkg: error processing package virtenginevnc (--purge):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 virtenginevnc
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rajesh-rajagopal** [comment]
Its fixed. close this issue.
